# Generated by Django 4.2.1 on 2023-06-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rating",
            name="star",
        ),
        migrations.AddField(
            model_name="rating",
            name="rating",
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name="RatingStar",
        ),
    ]
